dist: xenial
language: php
php:
  - '7.2'
  - '7.3'

install:
  - composer install

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 src
  - ./vendor/bin/phpcs --standard=PSR2 test
  - ./vendor/bin/phpmd src text phpmd.xml
